// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD22PQZRTPFLZntl1gb1TPcCXd8CpOruRM',
    appId: '1:244829638667:web:5190e8e7f2e1fa265d770e',
    messagingSenderId: '244829638667',
    projectId: 'jewlease-dfd65',
    authDomain: 'jewlease-dfd65.firebaseapp.com',
    storageBucket: 'jewlease-dfd65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboS8BXAlkdPfwNeB7iLLE7XFdS1plKvY',
    appId: '1:244829638667:android:66cdda4324211e7d5d770e',
    messagingSenderId: '244829638667',
    projectId: 'jewlease-dfd65',
    storageBucket: 'jewlease-dfd65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaDFQzQhjIdVvXIINiV5L_g4JcGkrSKik',
    appId: '1:244829638667:ios:726e63abbdae062c5d770e',
    messagingSenderId: '244829638667',
    projectId: 'jewlease-dfd65',
    storageBucket: 'jewlease-dfd65.appspot.com',
    iosBundleId: 'com.example.jewlease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaDFQzQhjIdVvXIINiV5L_g4JcGkrSKik',
    appId: '1:244829638667:ios:726e63abbdae062c5d770e',
    messagingSenderId: '244829638667',
    projectId: 'jewlease-dfd65',
    storageBucket: 'jewlease-dfd65.appspot.com',
    iosBundleId: 'com.example.jewlease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD22PQZRTPFLZntl1gb1TPcCXd8CpOruRM',
    appId: '1:244829638667:web:c4d547ec9b1793045d770e',
    messagingSenderId: '244829638667',
    projectId: 'jewlease-dfd65',
    authDomain: 'jewlease-dfd65.firebaseapp.com',
    storageBucket: 'jewlease-dfd65.appspot.com',
  );
}
